# Gives a new shape to an array without changing its data.

## Import numpy

In [2]:
import numpy as np

## This is our sample matrix

In [3]:
z = np.array([[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]])

## Lets print the shape of it

In [5]:
z.shape

(3, 4)

## Now lets reshape this matrix

In [6]:
z.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

### What happenned here was we have reshaped the matrix to 6 rows and 2 columns

### We can use -1 if we dont know the value of one dimention of the matrix. Suppose I dont know the value of rows but I know the value of column as 12, I can use reshape(-1,12). Here the -1 indicates that I dont know the value for row.

In [7]:
z.reshape(-1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

### Lets convert z 

In [8]:
z = z.reshape(-1, 12)

In [9]:
z

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

### Now lets see the shape of z

In [10]:
z.shape

(1, 12)

### Now lets try with -1 in the place of column

In [11]:
z = z.reshape(12, -1)

In [12]:
z

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

### shape of z

In [13]:
z.shape

(12, 1)

### Now lets try with one input

In [14]:
z = z.reshape(-1)

In [15]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### shape of z

In [16]:
z.shape

(12,)

### This is a vector

### Now lets try with both rows and columns as -1

In [17]:
z.reshape(-1, -1)

ValueError: can only specify one unknown dimension

### This will throw an error. We cannot use reshape if both row and column are unknown